### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by xiucz** [informationsea/tableview#2]
Hi, 
Thanks for your great job.

I use the tool for about 54549 line tsv file. 
![image](https://user-images.githubusercontent.com/12706146/130162976-c8f6d14e-b76c-43c1-bddf-7da9fd6ca384.png)

**Comment by xiucz** [comment]
```
goroutine 34 [running]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20200418040025-38ba6e5628f1/api.go:359 +0x905
main.(*Display).loadAllData.func2(0xc000452060)
	/home/travis/gopath/src/github.com/informationsea/tableview/main.go:337 +0x34
created by main.(*Display).loadAllData
	/home/travis/gopath/src/github.com/informationsea/tableview/main.go:335 +0x106

```
